import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex h-screen flex-col">
          <Navbar />
          <div className="flex-1 overflow-auto">
            <div className="flex h-full flex-col justify-between">
              <main>{children}</main>
              <footer className="">hello</footer>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
