import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Navbar from './navbar';
import GlassCard from '@/components/GlassCard';

// import ZustandProvider from '../providers/zustand-provider';
import TanStackProvider from '../providers/tanstack-provider';

import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex h-screen flex-col`}>
        <Navbar />
        <main className="flex-1">
          <section className="container flex h-full flex-col">
            <TanStackProvider>
              <GlassCard className="my-4 flex flex-1 flex-col justify-between rounded-md">
                {children}
              </GlassCard>
            </TanStackProvider>
          </section>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
